#:schema node_modules/wrangler/config-schema.json
name = "bolt"
compatibility_flags = ["nodejs_compat", "nodejs_als"]
compatibility_date = "2024-07-01"
pages_build_output_dir = "./build/client"

[build]
command = "pnpm run build"

[build.upload]
format = "modules"
